// Generated by CoffeeScript 1.6.3
(function() {
  var url, xhr;

  url = "http://api.flickr.com/services/feeds/photos_public.gne?format=json&jsoncallback=?";

  xhr = $.getJSON(url, function(data, success, xhr) {
    return $.each(data.items, function(i, photo) {
      var s;
      s = "<li>\n<a href=\"#\">\n<img src=\"" + photo.media.m + "\" />\n</a></li>";
      s = $(s);
      $('#images').append(s);
      return setTimeout(function() {
        return s.addClass('show');
      }, 500 * i);
    });
  });

}).call(this);
